# -*- coding: utf-8 -*-
"""train_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GijHmJctzbCgB7BD4sTKl-cf2XhfIRJx
"""

!pip install --upgrade torchao

# -*- coding: utf-8 -*-
"""
Support Ticket Severity Classifier - Training Pipeline
Handles heuristic pseudo-labeling and DeBERTa LoRA fine-tuning.
"""

import os
import re
import sys
import json
import math
import pickle
import argparse
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split
from sklearn.metrics import cohen_kappa_score, accuracy_score, f1_score, confusion_matrix, classification_report
from sklearn.utils import resample
from scipy.stats import spearmanr
from transformers import AutoTokenizer, AutoModelForSequenceClassification, get_cosine_schedule_with_warmup
from peft import LoraConfig, get_peft_model, TaskType, PeftModel

warnings.filterwarnings("ignore")

# --- Configuration & Constants ---
SEED_VAL = 42
BASE_MODEL = "microsoft/deberta-v3-small"

ORDINAL_MAP = {'Low': 0, 'Medium': 1, 'High': 2, 'Critical': 3}
REVERSE_MAP = {val: key for key, val in ORDINAL_MAP.items()}

# Keyword Patterns
CRITICAL_TERMS = [r'\bphish\w*\b', r'\bfraud\w*\b', r'\bhack\w*\b', r'\bstolen\b', r'\bunauthori[sz]ed\b', r'\bdata\s+breach\b', r'\bransomware\b', r'\bmalware\b', r'\bidentity\s+theft\b', r'\bcompromised\b']
HIGH_TERMS = [r'\bcrash\w*\b', r'\bnot\s+(loading|working|responding|syncing)\b', r'\bcannot\s+(access|log)', r'\boutage\b', r'\blocke?d\s+out\b', r'\bpayment\s+fail\w*\b', r'\bdata\s+loss\b', r'\bbroken\b', r'\berror\b', r'\bdown\b', r'\bunable\s+to\b', r'\bcorrupt\w*\b']
LOW_TERMS = [r'\bhow\s+do\s+i\b', r'\bwhere\s+is\b', r'\bheadquarters\b', r'\broadmap\b', r'\bfeature\s+request\b', r'\bhours\s+of\s+operation\b']
URGENT_TERMS = [r'\bimmediately\b', r'\burgent\b', r'\basap\b', r'\bcritical\b']

CATEGORY_WEIGHTS = {'Fraud': 0.88, 'Technical': 0.52, 'Account': 0.38, 'Billing': 0.30, 'General Inquiry': 0.08}
LEXICAL_CAT_BASES = {'Fraud': 0.82, 'Technical': 0.50, 'Account': 0.36, 'Billing': 0.30, 'General Inquiry': 0.10}

SEVERE_WORDS = set("cannot access locked stolen phishing fraud hacked unauthorized crash error fail broken outage down missing corrupted urgent data loss breach malware ransomware compromised account suspended payment charge suspicious unable sync attack security".split())
ROUTINE_WORDS = set("how where question general inquiry feature request roadmap headquarters information looking update plan curious wondering schedule".split())

# --- Stage 1: Heuristic Processors ---

def evaluate_keywords(record):
    """Calculates an urgency score based on regex pattern matching."""
    combined_text = str(record.get('Ticket_Subject', '') + " " + record.get('Ticket_Description', '')).lower()

    score = 0.0
    for pattern in CRITICAL_TERMS:
        if re.search(pattern, combined_text): score += 0.32
    for pattern in HIGH_TERMS:
        if re.search(pattern, combined_text): score += 0.20
    for pattern in LOW_TERMS:
        if re.search(pattern, combined_text): score -= 0.14
    for pattern in URGENT_TERMS:
        if re.search(pattern, combined_text): score += 0.14

    normalized_text_score = float(np.clip(score / (abs(score) + 3.0 + 1e-9), 0.0, 1.0)) if score != 0 else 0.0
    cat_influence = CATEGORY_WEIGHTS.get(record.get('Issue_Category'), 0.30)

    return float(np.clip(0.60 * normalized_text_score + 0.40 * cat_influence, 0.0, 1.0))

def extract_time_benchmarks(dataframe):
    """Generates median resolution times grouped by category and priority."""
    group_medians = dataframe.groupby(['Issue_Category', 'Priority_Level'])['Resolution_Time_Hours'].median().to_dict()
    global_medians = dataframe.groupby('Priority_Level')['Resolution_Time_Hours'].median().to_dict()
    return group_medians, global_medians

def calculate_time_anomaly(record, group_benchmarks, global_benchmarks):
    """Scores how far the actual resolution time deviates from the expected norm."""
    actual_hours = float(record['Resolution_Time_Hours'])
    current_priority = record['Priority_Level']
    priority_weight = ORDINAL_MAP[current_priority] / 3.0

    expected_hours = group_benchmarks.get((record['Issue_Category'], current_priority),
                                          global_benchmarks.get(current_priority, 36.0))

    time_ratio = actual_hours / max(expected_hours, 1.0)
    log_ratio = float(math.log(max(time_ratio, 0.01)))

    if log_ratio > 0:
        anomaly_signal = priority_weight * float(math.tanh(log_ratio * 0.8))
    else:
        anomaly_signal = (1.0 - priority_weight) * float(math.tanh(-log_ratio * 0.5))

    return float(np.clip(anomaly_signal, 0.0, 1.0))

def compute_lexical_density(record):
    """Analyzes pure word counts for severe vs routine terminology."""
    raw_text = f"{record['Ticket_Subject']} {record['Ticket_Description']}".lower()
    tokens = re.findall(r'\b\w+\b', raw_text)

    if not tokens:
        return 0.3

    word_count = len(tokens)
    severe_ratio = sum(1 for w in tokens if w in SEVERE_WORDS) / word_count
    routine_ratio = sum(1 for w in tokens if w in ROUTINE_WORDS) / word_count

    lexical_val = float(np.clip((severe_ratio * 14.0) - (routine_ratio * 7.0), 0.0, 1.0))
    satisfaction_val = (5.0 - int(record['Satisfaction_Score'])) / 4.0
    category_val = LEXICAL_CAT_BASES.get(record['Issue_Category'], 0.28)

    return float(np.clip((0.45 * lexical_val) + (0.35 * satisfaction_val) + (0.20 * category_val), 0.0, 1.0))

def extract_semantic_clusters(dataframe, export_path):
    """Builds semantic embeddings and clusters them to find latent severity groups."""
    corpus = dataframe.apply(lambda r: f"{r['Ticket_Subject']}. {r['Ticket_Description']} cat:{r['Issue_Category']} ch:{r['Ticket_Channel']}", axis=1).tolist()

    # Embedding generation
    try:
        from sentence_transformers import SentenceTransformer
        encoder = SentenceTransformer('all-MiniLM-L6-v2')
        embeddings = encoder.encode(corpus, batch_size=64, show_progress_bar=True, normalize_embeddings=True)
    except ImportError:
        from sklearn.feature_extraction.text import TfidfVectorizer
        from sklearn.decomposition import TruncatedSVD
        from sklearn.preprocessing import normalize
        vectorizer = TfidfVectorizer(max_features=6000, ngram_range=(1, 2), sublinear_tf=True)
        sparse_matrix = vectorizer.fit_transform(corpus)
        embeddings = normalize(TruncatedSVD(n_components=100, random_state=SEED_VAL).fit_transform(sparse_matrix))

    # Dimensionality reduction
    try:
        import umap
        reducer = umap.UMAP(n_components=8, n_neighbors=15, min_dist=0.05, metric='cosine', random_state=SEED_VAL, verbose=False)
        reduced_embeddings = reducer.fit_transform(embeddings)
    except ImportError:
        from sklearn.decomposition import PCA
        n_comps = min(8, embeddings.shape[1] - 1)
        reduced_embeddings = PCA(n_components=n_comps, random_state=SEED_VAL).fit_transform(embeddings)

    # Clustering
    try:
        import hdbscan
        clusterer = hdbscan.HDBSCAN(min_cluster_size=30, min_samples=8, metric='euclidean')
        assigned_labels = clusterer.fit_predict(reduced_embeddings)
    except ImportError:
        from sklearn.cluster import KMeans
        clusterer = KMeans(n_clusters=12, random_state=SEED_VAL, n_init=10)
        assigned_labels = clusterer.fit_predict(reduced_embeddings)

    # Scoring clusters
    dataframe['cluster_id'] = assigned_labels
    cluster_means = {
        cid: dataframe[dataframe['cluster_id'] == cid]['priority_numeric'].mean()
        for cid in set(assigned_labels) if cid != -1
    }

    if cluster_means:
        min_val, max_val = min(cluster_means.values()), max(cluster_means.values())
        signals = []
        for cid in assigned_labels:
            if cid == -1:
                signals.append(0.5)
            else:
                score = (cluster_means.get(cid, min_val) - min_val) / (max_val - min_val + 1e-9)
                signals.append(float(np.clip(score, 0.0, 1.0)))
    else:
        signals = [0.5] * len(dataframe)

    np.save(str(export_path / 'emb_reduced.npy'), reduced_embeddings)
    np.save(str(export_path / 'cluster_ids.npy'), assigned_labels)

    return np.array(signals)

def apply_heuristic_fusion(dataframe, export_dir, model_dir):
    """Combines the 4 individual signals using a Logistic Regression model to create the final pseudo-label."""
    signal_cols = ['sig_kw', 'sig_rt', 'sig_lex', 'sig_sem']
    friendly_names = {'sig_kw': 'Keywords', 'sig_rt': 'Time Anomalies', 'sig_lex': 'Lexical/CSAT', 'sig_sem': 'Semantic Group'}

    print("\n--- Evaluating Signal Agreements ---")
    for idx, feature1 in enumerate(signal_cols):
        for feature2 in signal_cols[idx + 1:]:
            bool1 = (dataframe[feature1] >= 0.5).astype(int)
            bool2 = (dataframe[feature2] >= 0.5).astype(int)
            kappa = cohen_kappa_score(bool1, bool2)
            match_pct = (bool1 == bool2).mean() * 100
            print(f"[{friendly_names[feature1]:<15} & {friendly_names[feature2]:<15}] Kappa: {kappa:.3f} | Match: {match_pct:.1f}%")

    stats_report = {}
    print("\n--- Feature Correlation ---")
    for feature in signal_cols:
        corr_rho, _ = spearmanr(dataframe[feature], dataframe['priority_numeric'])

        # Calculate how often the signal gets the priority within +/- 1 level
        quantized = dataframe[feature].apply(lambda v: 3 if v >= 0.75 else (2 if v >= 0.50 else (1 if v >= 0.25 else 0)))
        accuracy_at_1 = ((quantized - dataframe['priority_numeric']).abs() <= 1).mean()

        stats_report[friendly_names[feature]] = {'spearman_rho': round(corr_rho, 4), 'acc_within_1': round(accuracy_at_1, 4)}
        print(f"{friendly_names[feature]:<18} Rho: {corr_rho:.3f} | Acc@1: {accuracy_at_1 * 100:.1f}%")

    features_matrix = dataframe[signal_cols].values
    target_vector = (dataframe['priority_numeric'] >= 2).astype(int).values

    scaler = StandardScaler()
    scaled_features = scaler.fit_transform(features_matrix)

    classifier = LogisticRegression(C=1.0, class_weight='balanced', max_iter=500, random_state=SEED_VAL)
    kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED_VAL)

    acc_scores = cross_val_score(classifier, scaled_features, target_vector, cv=kfold, scoring='accuracy')
    f1_scores = cross_val_score(classifier, scaled_features, target_vector, cv=kfold, scoring='f1_macro')

    print(f"\nFusion Classifier CV -> Accuracy: {acc_scores.mean():.3f} (±{acc_scores.std():.3f}) | F1: {f1_scores.mean():.3f} (±{f1_scores.std():.3f})")

    classifier.fit(scaled_features, target_vector)
    dataframe['severity_probability'] = classifier.predict_proba(scaled_features)[:, 1]

    feature_weights = dict(zip(signal_cols, np.abs(classifier.coef_[0])))
    weight_sum = sum(feature_weights.values()) + 1e-9

    print("\nFinal Feature Importances:")
    for feature_key, weight_val in sorted(feature_weights.items(), key=lambda item: -item[1]):
        percentage = (weight_val / weight_sum) * 100
        stats_report[friendly_names[feature_key]]['fusion_weight_pct'] = round(percentage, 1)
        print(f"{friendly_names[feature_key]:<18}: {percentage:.1f}%")

    with open(export_dir / 'ablation_table.json', 'w') as jfile:
        json.dump(stats_report, jfile, indent=2)

    with open(model_dir / 'fusion_model.pkl', 'wb') as pfile:
        pickle.dump({'model': classifier, 'scaler': scaler, 'cols': signal_cols}, pfile)

    return dataframe

def tag_data_discrepancies(dataframe):
    """Categorizes tickets based on the delta between assigned and inferred priorities."""
    def convert_score_to_label(score):
        if score >= 0.75: return 'Critical'
        if score >= 0.50: return 'High'
        if score >= 0.25: return 'Medium'
        return 'Low'

    dataframe['calculated_severity'] = dataframe['severity_probability'].apply(convert_score_to_label)
    dataframe['calculated_numeric'] = dataframe['calculated_severity'].map(ORDINAL_MAP)
    dataframe['priority_delta'] = dataframe['calculated_numeric'] - dataframe['priority_numeric']

    # Mark as mismatch if the gap is 2 levels or more
    dataframe['is_mismatch'] = (dataframe['priority_delta'].abs() >= 2).astype(int)

    def determine_mismatch_type(row):
        if row['is_mismatch'] == 0:
            return 'Consistent'
        return 'Hidden Crisis' if row['priority_delta'] >= 2 else 'False Alarm'

    dataframe['discrepancy_type'] = dataframe.apply(determine_mismatch_type, axis=1)

    print(f"\nOverall Discrepancy Rate: {dataframe['is_mismatch'].mean() * 100:.1f}%")
    print("Breakdown:")
    print(dataframe['discrepancy_type'].value_counts().to_string())

    return dataframe

def execute_phase_one(dataset_path, export_dir, model_dir):
    print("=" * 60)
    print(" PHASE 1: GENERATING HEURISTIC PSEUDO-LABELS")
    print("=" * 60)

    dataset = pd.read_csv(dataset_path)
    dataset['priority_numeric'] = dataset['Priority_Level'].map(ORDINAL_MAP)
    print(f"Imported {len(dataset):,} raw records.")

    print("=> Processing Rule-Based Keywords...")
    dataset['sig_kw'] = dataset.apply(evaluate_keywords, axis=1)

    print("=> Processing Resolution Time Deviations...")
    grouped_b, global_b = extract_time_benchmarks(dataset)
    dataset['sig_rt'] = dataset.apply(lambda r: calculate_time_anomaly(r, grouped_b, global_b), axis=1)

    print("=> Processing Lexical & CSAT Context...")
    dataset['sig_lex'] = dataset.apply(compute_lexical_density, axis=1)

    print("=> Processing Semantic Clustering Space...")
    dataset['sig_sem'] = extract_semantic_clusters(dataset, export_dir)

    dataset = apply_heuristic_fusion(dataset, export_dir, model_dir)
    dataset = tag_data_discrepancies(dataset)

    output_file = export_dir / 'labeled_tickets.csv'
    dataset.to_csv(output_file, index=False)
    print(f"\nPhase 1 Complete. Dataset saved to {output_file}")

    return dataset

# --- Stage 2: Deep Learning Training ---

def categorise_time(hours):
    if hours <= 10: return 'FAST'
    if hours <= 45: return 'MID'
    return 'SLOW'

def format_text_prompt(record):
    """Formats the structured data into a prompt for the language model."""
    res_time = float(record.get('Resolution_Time_Hours', 30.0))
    time_bracket = categorise_time(res_time)

    return (f"[SUBJ] {record['Ticket_Subject']} "
            f"[BODY] {record['Ticket_Description']} "
            f"| cat:{record['Issue_Category']} "
            f"| ch:{record['Ticket_Channel']} "
            f"| rt:{time_bracket} "
            f"| pri:{record['Priority_Level']}")

class SupportTicketDataset(Dataset):
    def __init__(self, raw_texts, target_labels, tokenizer):
        self.encodings = tokenizer(
            list(raw_texts),
            truncation=True,
            padding='max_length',
            max_length=256,
            return_tensors='pt'
        )
        self.labels = torch.tensor(target_labels, dtype=torch.long)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, index):
        item = {key: tensor[index] for key, tensor in self.encodings.items()}
        item['labels'] = self.labels[index]
        return item

def evaluate_model(model_obj, dataloader, hardware_device, prob_threshold=0.5):
    """Helper function to run inference on a validation/test dataloader."""
    model_obj.eval()
    all_probabilities, all_targets = [], []

    with torch.no_grad():
        for batch in dataloader:
            inputs = batch['input_ids'].to(hardware_device)
            masks = batch['attention_mask'].to(hardware_device)
            outputs = model_obj(input_ids=inputs, attention_mask=masks)

            # Extract probability for the positive class (Mismatch)
            probs = torch.softmax(outputs.logits.float(), dim=-1)[:, 1].cpu().tolist()
            all_probabilities.extend(probs)
            all_targets.extend(batch['labels'].tolist())

    prob_array = np.array(all_probabilities)
    target_array = np.array(all_targets)
    predictions = (prob_array >= prob_threshold).astype(int)

    acc = accuracy_score(target_array, predictions)
    macro_f1 = f1_score(target_array, predictions, average='macro', zero_division=0)
    class_f1 = f1_score(target_array, predictions, average=None, zero_division=0)

    return acc, macro_f1, class_f1, prob_array, target_array

def execute_phase_two(dataset, model_path, total_epochs, batch_capacity):
    print("\n" + "=" * 60)
    print(" PHASE 2: DEBERTA-V3 FINE-TUNING VIA LORA")
    print("=" * 60)

    hardware = 'cuda' if torch.cuda.is_available() else 'cpu'
    if hardware == 'cuda':
        print(f"Hardware utilized: GPU | {torch.cuda.get_device_name(0)}")
    else:
        print("Hardware utilized: CPU")

    text_columns = ['Ticket_Subject', 'Ticket_Description', 'Issue_Category', 'Ticket_Channel', 'Priority_Level']
    for col in text_columns:
        dataset[col] = dataset[col].astype(str)

    dataset['model_input'] = dataset.apply(format_text_prompt, axis=1)
    features = dataset['model_input'].values
    targets = dataset['is_mismatch'].values.astype(int)

    # Standard split: Train, Val, Test
    x_temp, x_test, y_temp, y_test = train_test_split(features, targets, test_size=0.10, stratify=targets, random_state=SEED_VAL)
    x_train, x_val, y_train, y_val = train_test_split(x_temp, y_temp, test_size=0.111, stratify=y_temp, random_state=SEED_VAL)

    # Class balancing via upsampling the minority class
    x_majority = x_train[y_train == 0]
    y_majority = y_train[y_train == 0]
    x_minority = x_train[y_train == 1]
    y_minority = y_train[y_train == 1]

    upsample_count = len(x_majority) // 3
    x_min_upsampled = resample(x_minority, n_samples=upsample_count, replace=True, random_state=SEED_VAL)

    x_balanced = np.concatenate([x_majority, x_min_upsampled])
    y_balanced = np.concatenate([y_majority, np.ones(upsample_count, dtype=int)])

    # Shuffle the balanced dataset
    shuffler = np.random.RandomState(SEED_VAL)
    shuffle_indices = shuffler.permutation(len(x_balanced))
    x_balanced, y_balanced = x_balanced[shuffle_indices], y_balanced[shuffle_indices]

    print(f"\nData Splits -> Train: {len(x_balanced):,} | Val: {len(x_val):,} | Test: {len(x_test):,}")
    print(f"Balanced Breakdown -> Consistent: {(y_balanced == 0).sum():,} | Mismatch: {(y_balanced == 1).sum():,}")

    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
    train_data = SupportTicketDataset(x_balanced, y_balanced, tokenizer)
    val_data = SupportTicketDataset(x_val, y_val, tokenizer)
    test_data = SupportTicketDataset(x_test, y_test, tokenizer)

    train_loader = DataLoader(train_data, batch_size=batch_capacity, shuffle=True)
    val_loader = DataLoader(val_data, batch_size=32)
    test_loader = DataLoader(test_data, batch_size=32)

    # Setup foundation model and LoRA adapter
    foundation_model = AutoModelForSequenceClassification.from_pretrained(BASE_MODEL, num_labels=2, ignore_mismatched_sizes=True)

    lora_settings = LoraConfig(
        task_type=TaskType.SEQ_CLS,
        r=16,
        lora_alpha=32,
        lora_dropout=0.1,
        bias='none',
        target_modules=['query_proj', 'key_proj', 'value_proj', 'out_proj'],
        modules_to_save=['classifier', 'pooler']
    )

    active_model = get_peft_model(foundation_model, lora_settings).float().to(hardware)
    params_trainable, params_total = active_model.get_nb_trainable_parameters()
    print(f"\nParameters: {params_trainable:,} trainable out of {params_total:,} ({100 * params_trainable / params_total:.2f}%)")

    # Dynamic class weighting
    count_0 = (y_balanced == 0).sum()
    count_1 = (y_balanced == 1).sum()
    total_count = len(y_balanced)

    class_weights = torch.tensor([total_count / (2 * count_0), total_count / (2 * count_1)], dtype=torch.float).to(hardware)
    criterion = nn.CrossEntropyLoss(weight=class_weights)

    # Training configuration
    GRADIENT_ACCUMULATION = 2
    LEARNING_RATE = 3e-5
    total_optimization_steps = (len(train_loader) // GRADIENT_ACCUMULATION) * total_epochs
    warmup_steps = int(0.06 * total_optimization_steps)

    optimizer = AdamW(active_model.parameters(), lr=LEARNING_RATE, weight_decay=0.01)
    lr_scheduler = get_cosine_schedule_with_warmup(optimizer, num_warmup_steps=warmup_steps, num_training_steps=total_optimization_steps)

    print(f"\nConfig: {total_epochs} Epochs | Batch: {batch_capacity} | Accumulation: {GRADIENT_ACCUMULATION} | LR: {LEARNING_RATE}")
    print("-" * 50)
    print(f"{'Epoch':<6} | {'Avg Loss':<10} | {'Val Acc':<10} | {'Val F1':<10}")
    print("-" * 50)

    top_f1 = 0.0
    top_epoch = 0
    training_history = {'loss': [], 'val_f1': []}

    optimizer.zero_grad()

    # Training Loop
    for current_epoch in range(1, total_epochs + 1):
        active_model.train()
        running_loss = 0.0

        for step, batch_data in enumerate(train_loader, start=1):
            inputs_gpu = batch_data['input_ids'].to(hardware)
            masks_gpu = batch_data['attention_mask'].to(hardware)
            labels_gpu = batch_data['labels'].to(hardware)

            predictions = active_model(input_ids=inputs_gpu, attention_mask=masks_gpu)
            loss = criterion(predictions.logits.float(), labels_gpu) / GRADIENT_ACCUMULATION

            loss.backward()
            running_loss += loss.item() * GRADIENT_ACCUMULATION

            if step % GRADIENT_ACCUMULATION == 0:
                nn.utils.clip_grad_norm_(active_model.parameters(), max_norm=1.0)
                optimizer.step()
                lr_scheduler.step()
                optimizer.zero_grad()

        # Validation step
        v_acc, v_f1, _, _, _ = evaluate_model(active_model, val_loader, hardware)
        avg_train_loss = running_loss / len(train_loader)

        training_history['loss'].append(avg_train_loss)
        training_history['val_f1'].append(v_f1)

        print(f" {current_epoch:<5} |  {avg_train_loss:<9.4f} |  {v_acc * 100:<7.2f}%  |  {v_f1:<8.4f}")

        # Save best weights
        if v_f1 > top_f1:
            top_f1 = v_f1
            top_epoch = current_epoch
            active_model.save_pretrained(str(model_path / 'best'))
            tokenizer.save_pretrained(str(model_path / 'best'))

    print(f"\n--- Training Complete. Best Epoch: {top_epoch} (F1: {top_f1:.4f}) ---")

    # Load best weights for threshold tuning and final testing
    best_foundation = AutoModelForSequenceClassification.from_pretrained(BASE_MODEL, num_labels=2, ignore_mismatched_sizes=True)
    optimal_model = PeftModel.from_pretrained(best_foundation, str(model_path / 'best')).float().to(hardware)

    # Threshold optimization
    _, _, _, val_probs, val_labels = evaluate_model(optimal_model, val_loader, hardware)
    optimal_threshold = 0.50
    highest_search_f1 = 0.0

    for candidate_thresh in np.linspace(0.20, 0.80, 61):
        temp_preds = (val_probs >= candidate_thresh).astype(int)
        temp_f1 = f1_score(val_labels, temp_preds, average='macro', zero_division=0)
        if temp_f1 > highest_search_f1:
            highest_search_f1 = temp_f1
            optimal_threshold = candidate_thresh

    print(f"\nOptimized Decision Boundary: {optimal_threshold:.2f} (Yields Validation F1: {highest_search_f1:.4f})")

    # Final Test Set Evaluation
    _, _, _, test_probs, test_labels = evaluate_model(optimal_model, test_loader, hardware)
    final_predictions = (test_probs >= optimal_threshold).astype(int)

    t_acc = accuracy_score(test_labels, final_predictions)
    t_f1 = f1_score(test_labels, final_predictions, average='macro', zero_division=0)
    conf_mat = confusion_matrix(test_labels, final_predictions)
    recalls = conf_mat.diagonal() / conf_mat.sum(axis=1)

    print(f"\n--- FINAL TEST RESULTS (Threshold = {optimal_threshold:.2f}) ---")
    print(classification_report(test_labels, final_predictions, target_names=['Consistent', 'Mismatch'], zero_division=0))
    print(f"Overall Accuracy:  {t_acc * 100:.2f}%  {'[PASS]' if t_acc >= 0.83 else '[FAIL]'}")
    print(f"Macro F1 Score:    {t_f1:.4f}     {'[PASS]' if t_f1 >= 0.82 else '[FAIL]'}")
    print(f"Recall Consistent: {recalls[0]:.4f}     {'[PASS]' if recalls[0] >= 0.78 else '[FAIL]'}")
    print(f"Recall Mismatch:   {recalls[1]:.4f}     {'[PASS]' if recalls[1] >= 0.78 else '[FAIL]'}")

    # Final saving
    active_model.save_pretrained(str(model_path))
    tokenizer.save_pretrained(str(model_path))
    np.save(str(model_path / 'threshold.npy'), np.array([optimal_threshold]))

    run_metrics = {
        'accuracy': t_acc,
        'macro_f1': t_f1,
        'recall_consistent': float(recalls[0]),
        'recall_mismatch': float(recalls[1]),
        'threshold': float(optimal_threshold),
        'confusion_matrix': conf_mat.tolist(),
        'best_epoch': top_epoch,
        'history': training_history,
    }

    with open(model_path / 'metrics.json', 'w') as mf:
        json.dump(run_metrics, mf, indent=2)

    print(f"Models and metrics successfully persisted to: {model_path}")

def run_application():
    parser = argparse.ArgumentParser(description="Customer Support Severity Assessment Pipeline")
    parser.add_argument('--data', default='/content/customer_support_tickets.csv', help="Path to input raw dataset")
    parser.add_argument('--output-dir', default='outputs', help="Directory for generated datasets and logs")
    parser.add_argument('--model-dir', default='models/sia_model', help="Directory to save PyTorch models")
    parser.add_argument('--epochs', type=int, default=6, help="Training cycles")
    parser.add_argument('--batch-size', type=int, default=16, help="Data per batch")
    parser.add_argument('--skip-stage1', action='store_true', help="Bypass heuristics if pseudolabels already exist")

    # Passed empty array so this runs smoothly in notebooks without pulling sys.argv
    args = parser.parse_args(args=[])

    out_folder = Path(args.output_dir)
    mod_folder = Path(args.model_dir)

    out_folder.mkdir(parents=True, exist_ok=True)
    mod_folder.mkdir(parents=True, exist_ok=True)
    (mod_folder / 'best').mkdir(exist_ok=True)

    if args.skip_stage1:
        target_csv = out_folder / 'labeled_tickets.csv'
        if not target_csv.exists():
            sys.exit(f"Error: {target_csv} does not exist. Please run without --skip-stage1 first.")
        dataframe = pd.read_csv(target_csv)
    else:
        input_data_path = Path(args.data)
        if not input_data_path.exists():
            sys.exit(f"Error: Dataset {input_data_path} not found. Please verify the path.")
        dataframe = execute_phase_one(input_data_path, out_folder, mod_folder)

    execute_phase_two(dataframe, mod_folder, args.epochs, args.batch_size)
    print("\n[✔] Execution workflow finished successfully.")

if __name__ == '__main__':
    run_application()